drop table if exists board_table CASCADE;
create table board_table
(
    id bigint generated by default as identity,
    board_title varchar(255),
    board_writer varchar(20),
    board_contents varchar(500),
    board_pass varchar(255),
    board_hits int,
    file_attached int,
    created_time datetime,
    updated_time datetime,
    primary key (id)
);